remote_theme: pages-themes/leap-day@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: Experiment
description: Any new features to be merged to by homepage should be first tested here
# Hope this works
